# this the default target to compile the C++ program, which would be executed if you just run `make` without any arguments

# this compiles the 'main.cpp' file into an executable named 'main.out' using g++

hashtable: main.cpp
	g++ -Wall main.cpp -o main.out 

# this runs the executable 'main.out' generated by the default target above
# on Windows, use 'main.out' instead of './main.out'

run: main.out 
	main.out 

# this will delete all files with a `.out` extension in the current directory
# on Windows, use `del` instead of `rm`

clean:
	rm *.out 
